#!/bin/bash
# cindent
# Indent a file according to brace-aligned style, using tabs instead of spaces

for i in $@
do
	if [ -f "$1" ]
	then
		indent --tab-size 4 -bli0 -ci4 -ip4 -nlp -npcs -i 4 "$1"
		sed -r --in-place -e "s/\/\/\ */\/\/\ /g" "$1"
		sed -r --in-place -e "s/\ *$//g" "$1"
		sed -r --in-place -e "s/(\/\/.*\.)\ \ */\1 /g" "$1"
	else
		echo "File: \"$1\" does not exist."
	fi
	shift
done
