#!/bin/bash
# dell-deals
# Scans Dell's websites for whatever deals might be on

DEAL_1='http://accessories.us.dell.com/sna/ProductDetail.aspx?sku=222-0863&c=ca&l=en&cs=cadhs1&brandid=56&page=productlisting.aspx'
PRICE_1="2,299"
PRICE_OUTPUT_1=/tmp/dell-price1.txt
HTML_FILE=/tmp/dell.html
REGEX_PRICE='([0-9],)*[0-9]+\.[0-9]{2}'

#wget $DEAL_1 -O $HTML_FILE

egrep -o "<div class=\"para_marketingprice_simple\">\\$+${REGEX_PRICE}" $HTML_FILE \
	| egrep -o "${REGEX_PRICE}" \
	> $PRICE_OUTPUT_1

grep "$PRICE_1" $PRICE_OUTPUT_1 > /dev/null
result=$?

if [ $result -ne 0 ]; then
	echo "price changed!"
fi
