#!/bin/bash

REGEX='.*\.\(cpp\|hpp\|inl\|h\|hh\|c\|cc\|java\|asm\|py\|rb\|php\|js\|css\)$'

if [[ $# -gt 0 && -d $1 ]]; then
	DIR="$1"
	if [ -d "$DIR" ]; then
		shift
#		echo "find \"$DIR\" -regex $REGEX \"$@\""
		exec find "$DIR" -regex $REGEX "$@"
		exit 0
	fi
fi

# echo "find -regex \"$REGEX\" \"$@\""
exec find -regex "$REGEX" "$@"
