#!/bin/bash

if [[ $# -lt 1 || $# -gt 1 ]]; then
	echo "usage: $(basename $0) < git-repo | clear >"
	return 1
fi

REPO="$1"

case "$REPO" in
	'shell-scripts' ) GIT_DIR="$HOME/git/shell-scripts"; GIT_WORK_TREE="$HOME";;
	'sb2'           ) GIT_DIR="$HOME/git/sb2"; GIT_WORK_TREE="/";;
	'clear'         ) unset GIT_DIR; unset GIT_WORK_TREE;;
	*               ) echo "Invalid repo, please choose one from the list.";;
esac

echo "Setting git environment for \`$REPO'..."
echo "GIT_DIR = $GIT_DIR"
echo "GIT_WORK_TREE = $GIT_WORK_TREE"
export GIT_DIR GIT_WORK_TREE
