#!/bin/bash
# grep-source-files

if echo $0 | grep 'egrep'; then
	GREP=egrep
else
	GREP=grep
fi

PATTERN=$1
shift

if [[ $# -gt 0 && -d $1 ]]; then
	FIND_PATH=$1
	shift
fi

find-source-files "$FIND_PATH" -exec "$GREP" -Hn "$PATTERN" $* {} \;
