#!/bin/bash
# gt3
# Make three terminals

# top left
gnome-terminal --hide-menubar --geometry 146x77+0+0 &

# top right
gnome-terminal --hide-menubar --geometry 120x42+1095+0 &

# bottom right
gnome-terminal --hide-menubar --geometry 101x28+1053-70 &
