#!/bin/bash
# gt3
# Make three terminals

# top left
gnome-terminal --hide-menubar --geometry 134x41+0+0 -t "[1] 1" &

# top right
gnome-terminal --hide-menubar --geometry 132x41+1095+0 -t "[1] 2" &

# bottom left
gnome-terminal --hide-menubar --geometry 134x27+0-70 -t "[1] 3" &

# bottom right
gnome-terminal --hide-menubar --geometry 112x27+968-70 -t "[1] 4" &
