#!/bin/bash

if [ "$(basename $0)" == "vimf" ]; then
	EDITOR="vim"
elif [[ "$(basename $0)" == "gvimfc" || "$(basename $0)" == "xgvimcf" ]]; then
	EDITOR="gvimcode"
else
	EDITOR="gvim"
fi

if [ -d $1 ]; then
	DIR="$1"
	FILE_PATH="$2"
	FILE="$2"
	LINE="$(echo $2 | sed -e 's/^[^:]*:\([0-9]\+\).*/\1/g')"
else
	DIR=""
	FILE_PATH="$(echo $1 | sed -e 's/^\([^:]*\):.*/\1/g')"
	FILE="$(basename $FILE_PATH)"
	LINE="$(echo $1 | sed -e 's/^\([^:]*:\([0-9]\+\)\)\?.*/\2/g')"
fi

if echo $FILE | egrep ":[0-9]+(:.*)?$" > /dev/null 2>&1; then
	LINE="+$(echo $FILE | egrep -o "[0-9]+(:.*)?$" | egrep -o "^[0-9]+")"
	FILE="$(echo $FILE | egrep -o "^[^:]+")"
fi

if echo $FILE_PATH | egrep "\/" > /dev/null 2>&1; then
	# If the file name contains a full path
	if [ -f $FILE_PATH ]; then
		echo "$EDITOR +$LINE $FILE_PATH"
		$EDITOR +$LINE $FILE_PATH
	else
		ESCAPED_PATH=$(echo "$FILE_PATH" | sed -e 's/^[\.]\?[\/]\?//g' | sed -e 's/\//\\\//g')
		echo "find $DIR -regex \".*$ESCAPED_PATH\" -exec $EDITOR +$LINE {} \;"
		find $DIR -regex ".*$ESCAPED_PATH" -exec echo -n "+$LINE" \; \
			-exec echo " {}" \; \
			-exec $EDITOR "+$LINE" {} \;
	fi
else
	# If the file name has no path info
	echo "find $DIR -name $FILE -exec $EDITOR +$LINE {} \;"
	find $DIR -name $FILE -exec echo -n "+$LINE" \; \
		-exec echo " {}" \; \
		-exec $EDITOR "+$LINE" {} \;
fi
