#!/bin/bash
# myip

IFCONFIG=$(ifconfig | egrep -A 1 "^[A-Za-z0-9]+")
DEVS=$(ifconfig | egrep -o "^[A-Za-z0-9]+")
IPS=$(ifconfig | egrep -o "inet addr:[0-9]{1,3}.{1,3}.{1,3}.{1,3}" \
	| sed -e "s/inet addr://g")

echo "$IFCONFIG"
echo $DEVS
echo $IPS
