#!/bin/sh
MONTHLIST="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec"
DAYLIST="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 
25 26 27 28 29 30 31"

mkdir /tmp/ssg
for imonth in $MONTHLIST
do
    for iday in $DAYLIST
    do
        echo ${imonth}${iday}
        wget -q -O /tmp/ssg/${imonth}-${iday}-ssg.jpg -t 1 \
            http://sunshinegirl.canoe.ca/${imonth}${iday}/ssg.jpg > /dev/null
    done
done
