#!/bin/bash
# tminus
# counts down like spaceballs

DONE=0
while [ $DONE -eq 0 ]
do
	sleep 1s
	if [ `date | egrep -o ":[0-9]{2}:"` = ":00:" ]; then
		DONE=1
	fi
done

COUNT=$1
while [ $COUNT -gt 0 ]
do
	aumix -S
	aumix -v 95 -w 95
	speak "Tee minus $COUNT hours, and counting"
	aumix -L
	let COUNT-=1
	sleep 1h
done
