#!/bin/bash
# xinedvdjp
# plays all the vobs in the typical dvdrip directory
# plays japanese track and english subtitles

cd "$1"
pwd0=`pwd`

ls "$pwd0/vob/001/"*.vob > /tmp/xinedvd_playlist.txt
xine -P /tmp/xinedvd_playlist.txt -u 0 -a 1 --fullscreen
