#!/bin/bash
# cindent
# Indent a file according to brace-aligned style, using tabs instead of spaces

for file in $@
do
	if [ -f "$file" ]
	then
		dos2unix "$file"
		sed -r -i -e "s/\/\/\ */\/\/\ /g" "$file"
		sed -r -i -e "s/[\ \t]*$//g" "$file"

		indent \
			--tab-size 4 \
			-cbi0 \
			-bli0 \
			-ci4  \
			-ip4  \
			-nlp  \
			-npcs \
			-bap  \
			-bbo  \
			-br   \
			-blf  \
			-bls  \
			-ce   \
			-cdw  \
			-saf  \
			-sai  \
			-saw  \
			-i 4  \
			"$file"
	else
		echo "File: \"$file\" does not exist."
	fi
done
