#!/bin/bash
# uwhousing-list-houses
# lists the houses from the uw off-campus housing page

egrep -A 1 "span id=\"addresslink\"" "$1" \
	| grep -v "addresslink" \
	| egrep -o "[0-9][^<]*" \
	| sed -rs "s/([0-9]+)-([0-9]+)/\2/g" \
	| sed -rs "s/([0-9]+)(-[A-Za-z]+|[A-Za-z])/\1/g"
